name: Android CD

#発火条件
on:
  push:
    tags: '*ver.*'

jobs:
  build:
    #ビルド環境
    runs-on: ubuntu-latest

    steps:
      #リポジトリからソースをダンロード
      - uses: actions/checkout@v2
      #JAVA環境構築
      - name: install java 17.0.2
        uses: actions/setup-java@v1
        with:
          java-version: '17.0.2'

      - name: setup cache
        uses: actions/cache@v1
        with:
          path: /Users/runner/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache

      #Flutter環境構築
      - name: install flutter
        uses: subosito/flutter-action@v1
        with:
          #Flutterのバージョン
          flutter-version: '3.0.5'
          channel: 'stable'

      - name: flutter dependencies install
        #ライブラリーの導入
        run: flutter pub get

      - name: build apk
        run: |
          flutter build apk --release

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: android
          path: build/app/outputs/flutter-apk/app-release.apk
